# Generated by Django 6.0.4 on 2026-05-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("properties", "Properties"),
                    ("vehicles", "Vehicles"),
                    ("electronics", "Electronics"),
                    ("furniture", "Furniture"),
                    ("tools_equipment", "Tools & Equipment"),
                    ("agriculture_equipment", "Agriculture Equipment"),
                    ("sports_recreation", "Sports & Recreation"),
                ],
                default="electronics",
                max_length=30,
            ),
        ),
    ]
